### PR TITLE
Upgrade microk8s to 1.28

### PR DESCRIPTION
**Pull request by gboutry**
Microk8s 1.28 has serialized pulls disabled by default.

### CODE REVIEW

**Comment by gboutry** [comment]
/canonical/self-hosted-runners/run-workflows 38f986f

**Comment by gboutry** [comment]
/canonical/self-hosted-runners/run-workflows 38f986ff7bc769db1bb00c5be3efb6e41bfd4397

**Review by hemanthnakkina — APPROVED** [review]

**Comment by hemanthnakkina** [comment]
Can we check any impacts on snap-openstack in case of refresh of existing snap with microk8s 1.26-strict/stable installed.

**Comment by gboutry** [comment]
We can, but merging this in sunbeam-terraform shouldn't impact that ?

**Pull request merged**
