### PR TITLE
Add storage directives to applications

### PR DESCRIPTION
**Pull request by hemanthnakkina**
Add storage_directive to mysql-k8s, keystone-k8s,
glance-k8s, octavia-k8s, ovn-central-k8s apps.
Add mysql-storage-map to set storage directives for each mysql application for multi-mysql
deployment.

### CODE REVIEW

**Review by gboutry — DISMISSED** [review]

**Comment by hemanthnakkina** [comment]
Success in this run https://github.com/canonical/sunbeam-terraform/actions/runs/10209535864/job/28249343201?pr=83 but will try re-running the deploy workflow to see how consistent the success rate is.

**Comment by hemanthnakkina** [comment]
The PR should be in draft, waiting for fixes for https://github.com/juju/terraform-provider-juju/issues/534, https://github.com/juju/terraform-provider-juju/issues/537

**Comment by hemanthnakkina** [comment]
Testing this PR with snap-openstack here - https://github.com/canonical/snap-openstack/actions/runs/10901109321/job/30250569241?pr=290

**Comment by hemanthnakkina** [comment]
> Testing this PR with snap-openstack here - https://github.com/canonical/snap-openstack/actions/runs/10901109321/job/30250569241?pr=290

Bootstrap and enabling features are successful in the above snap-openstack PR functional test.
So marking this PR for ready for review

**Review by gboutry — APPROVED** [review]

**Pull request merged**
